import Head from "next/head";

import { collection, getDocs, limit, orderBy, query } from "firebase/firestore";
import { db } from "../firebase.config";

import CarouselSlider from "../components/Carousel.jsx";
import { useEffect, useState } from "react";
import LatestPostsPart from "../components/LatestPostsPart.jsx";
import RecentPostsPart from "../components/RecentPostsPart.jsx";

export default function Home({ posts }) {
  // console.log(posts);
  const colRef = collection(db, "posts");

  const latestPosts = posts.filter((post, i) => i <= 1);

  const [randomPosts, setRandomPosts] = useState([]);

  const recentPosts = posts.filter((post, i) => i > 1);

  const fetchRandomPosts = async () => {
    const posts = [];
    try {
      const snapshot = await getDocs(colRef);

      snapshot.docs
        .map((doc) => ({
          ...doc.data(),
          id: doc.id,
          timestamp: doc.data().timestamp.toDate().toDateString(),
        }))
        .sort(() => Math.random() - 0.5)
        .every((doc, i) => {
          if (i > 11) return false;
          posts.push({ ...doc });
          return true;
        });
      // console.log(posts);
      setRandomPosts(posts);
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    fetchRandomPosts();
  }, []);

  return (
    <>
      <Head>
        <title>Readis Thoughts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/newreadit.png" />
      </Head>

      <div className="mx-auto flex flex-col items-center justify-center space-y-6 ">
        <h2 className="text-5xl font-bold">Readis Thoughts</h2>
        <h2 className="text-6xl italic font-semibold text-orange-400">
          &quot;Blogs&quot;
        </h2>
        <p className="hidden sm:block max-w-sm text-center">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi,
          aspernatur accusamus. Odit!
        </p>
      </div>

      <LatestPostsPart latestPosts={latestPosts} />

      <CarouselSlider posts={randomPosts} />

      <RecentPostsPart recentPosts={recentPosts} headline={true} />
    </>
  );
}

export async function getStaticProps(context) {
  const colRef = collection(db, "posts");
  try {
    const q = query(colRef, orderBy("timestamp", "desc"), limit(14));

    const snapshot = await getDocs(q);

    const posts = [];
    snapshot.docs.forEach((doc) => {
      posts.push({
        ...doc.data(),
        id: doc.id,
        timestamp: doc.data().timestamp.toDate().toDateString(),
      });
    });

    return {
      revalidate: 600,
      props: {
        posts,
      },
    };
  } catch (error) {
    return {
      props: {
        posts: [],
      },
    };
  }
}
